### ISSUE TITLE
Rcpp is not imported when testing examples

### ISSUE THREAD

**Issue by yannabraham** [yannabraham/Radviz#17]
Error in optimizeAnchors(dataNormalized, classInds, freeVizSprings, attractG, :
     function 'enterRNGScope' not provided by package 'Rcpp'
    Calls: do.optimFreeviz -> optimizeAnchors
    Execution halted

**Comment by eddelbuettel** [comment]
Hi @yannabraham -- I randomly ended up here seeing the subject, and, given my familiarity with the error message ;-) took a look.

In essence, because the `Rcpp` package carries a little bit of stateful behaviour it needs to be imported too. One you do that, it all passes.  So the following suggested diff to one of the R files deals with both the Rcpp import and the `hexbin` import in #16 

```diff
modified   R/do.radviz.R
@@ -40,7 +40,9 @@
 #' @aliases do.radviz do.radviz.default
 #' 
 #' @importFrom ggplot2 ggplot aes_string geom_text xlim ylim coord_equal
-#' 
+#' @importFrom Rcpp evalCpp
+#' @import hexbin
+#'
 #' @aliases do.radviz do.radviz.default
 #' @author Yann Abraham
 #' @export
```

Happy to send you a PR if you want.   (The `import` for `hexbin` could possibly be narrower; I am not sure `geom_hex` calls.  Maybe `@importFrom hexbin hexbin` would do. I did not test that.  I did test the two lines above followed by a call to `roxygen2`.)

**Comment by yannabraham** [comment]
Hi @eddelbuettel thanks for the input, much appreciated! I will implement the fix you suggested and submit the updated package to CRAN shortly!

**Comment by eddelbuettel** [comment]
Great--that should take care of both the tickets you filed.   (And when you generate a fresh Rcpp package with one of the helper functions, this import is taken care of for you, though "in the old way".  Maybe I should add a roxygen example too one day.)
